# Generated by Django 5.2.3 on 2025-06-22 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField(blank=True)),
                ('hover_img_url', models.URLField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='figures.part')),
            ],
        ),
        migrations.CreateModel(
            name='UserFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_figures', to='figures.figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_figures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'figure')},
            },
        ),
    ]
